# Generated by Django 2.0.1 on 2018-01-24 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('A_value', models.FloatField(verbose_name='A Value')),
                ('B_value', models.FloatField(verbose_name='B Value')),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='A_value',
        ),
        migrations.RemoveField(
            model_name='site',
            name='B_value',
        ),
        migrations.RemoveField(
            model_name='site',
            name='date',
        ),
        migrations.AddField(
            model_name='entry',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
