# Generated by Django 2.0.1 on 2018-01-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='site',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
