# Generated by Django 2.0.1 on 2018-01-24 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20180124_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_site', to='sites.Site'),
        ),
    ]
